import * as yup from 'yup';

export const productSchema = yup.object().shape({
  name: yup.string().required('Product name is required').min(3, 'Product name must be at least 3 characters'),
  sku: yup.string().required('SKU is required'),
  category: yup.string().required('Category is required'),
  short_description: yup.string().required('Short description is required').max(150, 'Short description must not exceed 150 characters'),
  detailed_description: yup.string().max(2000, 'Detailed description must not exceed 2000 characters'),
  price: yup.number().typeError('Price must be a number').required('Price is required').moreThan(0, 'Price must be greater than 0'),
  compare_price: yup.number().typeError('Compare price must be a number').transform((value, originalValue) => (originalValue === '' ? null : value)).nullable(),
  cost_price: yup.number().typeError('Cost price must be a number').transform((value, originalValue) => (originalValue === '' ? null : value)).nullable(),
  stock_quantity: yup.number().typeError('Stock quantity must be a number').required('Stock quantity is required').min(0, 'Stock quantity cannot be negative'),
  low_stock_alert: yup.number().typeError('Low stock alert must be a number').transform((value, originalValue) => (originalValue === '' ? null : value)).nullable(),
  brand: yup.string().nullable(),
  fabric: yup.string().nullable(),
  color: yup.string().nullable(),
  size_type: yup.string().nullable(),
  gender: yup.string().nullable(),
  season: yup.string().nullable(),
  fit: yup.string().nullable(),
  weight: yup.string().nullable(),
  care_instructions: yup.string().nullable(),
  status: yup.string().nullable(),
  featured: yup.boolean(),
  best_seller: yup.boolean(),
  new_arrival: yup.boolean(),
  allow_backorders: yup.boolean(),
  measurement_required: yup.boolean(),
  allow_standard_sizes: yup.boolean(),
  allow_custom_notes: yup.boolean(),
  measurement_template: yup.string().nullable(),
  required_measurement_fields: yup.array().of(yup.string()),
  product_tags: yup.string().nullable(),
  meta_title: yup.string().nullable(),
  meta_description: yup.string().nullable(),
  slug: yup.string().nullable(),
  internal_notes: yup.string().nullable(),
  product_weight: yup.string().nullable(),
  package_length: yup.string().nullable(),
  package_width: yup.string().nullable(),
  package_height: yup.string().nullable(),
  shipping_class: yup.string().nullable(),
  delivery_time: yup.string().nullable(),
  return_policy: yup.string().nullable(),
  warranty: yup.string().nullable(),
  shipping_notes: yup.string().nullable(),
  images: yup.array().of(yup.string()).default([]),
});
